name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
version = "2.0.0-alpha.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4af6589f89842f5346301e43692829d7012b4acee3a64a4208e4239756f0b90"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
