
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 1074766292126543882
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18
#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "%player% allume le jeu."
	#The second line of text under the app name
	state = "Il arrive pour la collecte !"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% est sur le menu !"
	#The seconds line of text under the app name
	state = "A un clic du roleplay !"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% regarde la liste de serveurs"
	#The second line of text under the app name
	state = "HB ne lui suffit plus"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% cherche des Realms..."
	#The second line of text under the app name
	state = "Oui."
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% se connecte !"
	#The second line of text under the app name
	state = "Il pourra rejoindre le kiosque"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "%player% joue en solo !"
	#The second line of text under the app name
	state = "Le roleplay avec soit même, c'est cool !"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Joue ailleurs que sur HB..."
	#The second line of text under the app name
	state = "QUELLE HONTE !"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Il joue sur un realm"
	#The second line of text under the app name
	state = "Oui."
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Sûrement en train de roleplay"
	#The second line of text under the app name
	state = "Ou alors je dors sur mon clavier"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["icon_v4"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Herobrine.fr, but better !"
	#The Asset ID of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []
#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []
#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false
	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"
		#The first line of text under the app name
		description = "%player% is in The Overworld"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["overworld"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Overworld"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["mclogo"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"
		#The first line of text under the app name
		description = "%player% is in The Nether"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["nether"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Nether"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["mclogo"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"
		#The first line of text under the app name
		description = "%player% is in The End"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["end"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the End"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["mclogo"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []
