blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://discord.gg/CKBdqQrFf8
    about: General questions and support will be provided on the modpack's Discord
