name: Demande de mod
description: Suggérer un mod à ajouter dans in Herobrine.fr - Optimized
labels: mod
body:
- type: markdown
  attributes:
    value: |
      ## Mod name ⤴️
      Avant de demander un mod, [cherchez](https://github.com/HB-Modding-Crew/Herobrine.fr-Optimized/issues) si quelqu'un d'autre ne l'a pas demandé auparavant.
      Pour ce modpack, rester léger est important. [Veillez lire les principes du modpack](https://hb-modding-crew.gitbook.io/herobrine-optimized/general/principe) avant de faire votre demande.

- type: input
  attributes:
    label: Lien Curseforge
    description: Si le lien existe, renseignez le s'il vous plait.
    placeholder: https://www.curseforge.com/minecraft/mc-mods/...
  validations:
    required: false
      
- type: dropdown
  attributes:
    label: Distribution curseforge du mod
    description: Si le mod est sur CurseForge, remplissez le s'il vous plaît.
    multiple: false
    options:
      - Autorisée
      - Non autorisée
  validations:
    required: false
    
- type: markdown
  attributes:
    value: |
      1. Aller sur https://cflookup.com
      2. Collez le lien du mod dans "Project Id / Slug" et cliquez sur `Search project`
      3. Regardez la vleur `Mod Distribution` et sélectionnez la au dessus

- type: input
  attributes:
    label: Lien Modrinth
    description: Si le lien existe, renseignez le s'il vous plait.
    placeholder: https://modrinth.com/mod/...
  validations:
    required: false

- type: input
  attributes:
    label: Source ou autre lien
    description: Un repository Github par exemple. Optionel.
    placeholder: https://...
  validations:
    required: false

- type: textarea
  attributes:
    label: Description
    description: Une courte description du mod. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Pourquoi sur HB ?
    description: Comment le mod peut-il profiter à tout le monde tout en gardant l'expérience "vanilla-like"?
  validations:
    required: true

- type: textarea
  attributes:
    label: Points négatifs
    description: Les points négatifs qui pourraient gêner son intégration.
    placeholder: |
      Si le mod est bugué, instable, ou trop lourd. Si il n'est pas disponible sur Curseforge ou Modrinth. Si le mod est toujours en béta. Si il est trop complexe.
  validations:
      required: true
    
- type: textarea
  attributes:
    label: Autre
    description: Quelque chose à ajouter ?
  validations:
    required: false
