name: Bug report
description: Signaler un problème avec le modpack. Pour les mauvais FPS et les plantages, vous obtiendrez une réponse plus rapide de notre Discord
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Avant de signaler un problème, [veuillez rechercher](https://github.com/HB-Modding-Crew/Herobrine.fr-Optimized/issues) pour s'assurer qu'il n'a pas déjà été signalé. 

- type: textarea
  attributes:
    label: Décrivez le bug
    description: Décrivez votre problème. Pour les mauvais FPS et les plantages, vous obtiendrez une réponse plus rapide [sur notre Discord.](https://discord.gg/CKBdqQrFf8)
  validations:
    required: true

- type: input
  attributes:
    label: Version du modpack
    description: Quelle version du modpack utilisez vous ?
    placeholder: Le numéro de version est indiqué en bas à droite du menu principal de minecraft.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Quel launcher utilisez-vous ?
    options:
      - CurseForge Launcher
      - MultiMC
      - MultiMC (auto-update)
      - GDLauncher
      - Prism Launcher
      - Minecraft Launcher (vanilla)
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Autres détails
    description: Cochez au besoin.
    options:
      - label: J'ai mis à jour FO vers une version plus récente (mentionnez, quelle version vers quelle version)
      - label: J'ai ajouté/supprimé des mods ou des packs de ressources (mentionnez lesquels)
    
- type: textarea
  attributes:
    label: Contexte supplémentaire
    description: Captures d'écran, vidéo ou toute autre information. S'il s'agit d'un crash, merci de le poster sur [mclo.gs](https://mclo.gs/) et ajouter un lien ici.
    placeholder: |
      Conseil: Vous pouvez joindre des images ou des fichiers logs en cliquant sur cette zone pour la mettre en surbrillance, puis en faisant glisser les fichiers dedans.
  validations:
    required: false
