name: Setting change
description: Suggérer un changement d'option/config/keybind/etc dans un mod ou un outil existant
labels: option
body:
- type: markdown
  attributes:
    value: |
      Avant de demander un changement de configuration, [veuillez rechercher](https://github.com/HB-Modding-Crew/Herobrine.fr-Optimized/issues) s'il a déjà été demandé et voir [s'il a déjà été modifié](https://fabulously-optimized.gitbook.io/modpack/readme/changed-options). 
      S'il a été modifié et que vous ne le voyez pas, [assurez-vous que vous êtes sur la dernière version](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions) et [réinitialisez vos paramètres](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions#resetting-settings).

- type: textarea
  attributes:
    label: Quelle config changer
    description: Décrivez le changement que vous voulez que je fasse. Ce n'est PAS le lieu pour demander de nouvelles fonctionnalités qui n'existent pas déjà dans les mods inclus, demandez cela aux mods eux-mêmes.
  validations:
    required: true

- type: textarea
  attributes:
    label: Pourquoi devrait-il être changé
    description: Comment le changement peut-il profiter à tous tout en gardant l'expérience "vanilla-like" ?
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Détails supplémentaires
    description: Tout ce que vous voulez ajouter?
  validations:
    required: false
