name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
version = "2.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4155af292cf991ed49583dab33d6046f844091435c9f004f3ff568ac1088a4c"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
