name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
description = "Improve graphics and perfomances for roleplayers of Herobrine.fr"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"

[[Resource]]
name = "PACK_HB_FUTURE_VERSION"
filename = "PACK_HB_FUTURE_VERSION.zip"
action = "override"

[[Resource]]
name = "LonguesGlacesNeige"
filename = "LonguesGlacesNeige.zip"
action = "override"