name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
description = "Improve graphics and perfomances for roleplayers of Herobrine.fr"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"

[[Resource]]
name = "Lanternes_pack"
filename = "Lanternes_pack.zip"
action = "override"

[[Resource]]
name = "Lanternes_packrpo"
filename = "Lanternes_pack.zip.rpo"
action = "override"

[[Resource]]
name = "LonguesGlacesNeige"
filename = "LonguesGlacesNeige.zip"
action = "override"

[[Resource]]
name = "Litematica"
filename = "litematica-fabric-1.20.1-0.15.3.jar"
action = "override"

[[Resource]]
name = "MaLiLib"
filename = "malilib-fabric-1.20.1-0.16.1.jar"
action = "override"

[[Resource]]
name = "WorldEdit"
filename = "worldedit-mod-7.2.15.jar"
action = "override"

