name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
version = "2.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d0a4be0bdf239abd95527646c4830c28ea17de81ea481178b9b5b26537266be"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
