name = "Herobrine.fr - Optimized"
author = "Hb Modding Crew"
version = "2.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "266a16d2d56423512758fd19fe73344c673eafd55cb113de00d212ddcb73f964"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
